/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Dice: typeof import('./src/components/product/dice.vue')['default']
    EchartsDynamic: typeof import('./src/components/echarts/EchartsDynamic.vue')['default']
    EchartsDynamicOriginal: typeof import('./src/components/echarts/EchartsDynamicOriginal.vue')['default']
    FavoriteButton: typeof import('./src/components/product/favoriteButton.vue')['default']
    Footer: typeof import('./src/components/footer.vue')['default']
    Home: typeof import('./src/components/navbars/home.vue')['default']
    Login: typeof import('./src/components/login.vue')['default']
    Manage: typeof import('./src/components/navbars/manage.vue')['default']
    OrderAddDialog: typeof import('./src/components/myOrder/orderAddDialog.vue')['default']
    OrderTop: typeof import('./src/components/myOrder/orderTop.vue')['default']
    Product: typeof import('./src/components/navbars/product.vue')['default']
    ProductAddDialog: typeof import('./src/components/myProduct/productAddDialog.vue')['default']
    ProductCard: typeof import('./src/components/product/productCard.vue')['default']
    ProductCarousel: typeof import('./src/components/product/productCarousel.vue')['default']
    ProductTop: typeof import('./src/components/myProduct/productTop.vue')['default']
    QuestionSection: typeof import('./src/components/product/questionSection.vue')['default']
    RankingSidebar: typeof import('./src/components/product/rankingSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchDrawerFloating: typeof import('./src/components/searchDrawerFloating.vue')['default']
    SearchDrawerSide: typeof import('./src/components/searchDrawerSide.vue')['default']
  }
}
